#!/usr/bin/env bash
# print record type and IP address
print-domain(){
	record=$(dig "$2.$1" | awk 'NR == 13 {print $4}')
	dest=$(dig "$2.$1" | awk ' NR == 13 {print $5}')
	echo "The subdomain $2 is a $record  record and points to $dest"
}

if [ $# -ge 2 ]; then
	print-domain "$1" "$2"
else
	print-domain "$1" "www"
        print-domain "$1" "lb-01"
        print-domain "$1" "web-01"
        print-domain "$1" "web-02"
fi
