#!/usr/bin/env bash
#fix connection to port 80
#change Port
sed -i 's/listen [0-9]\+ default_server/listen 80 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/listen [::]:[0-9]\+ default_server/listen [::]:80 default_server/' /etc/nginx/sites-enabled/default
service nginx restart
