#!/usr/bin/env bash
# answer file to ufw
sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw default deny incomin
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable
